name: firebase_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.0
  firebase_analytics: ^10.10.2
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  firebase_ui_auth: ^1.13.1
  firebase_ui_oauth_google: ^1.3.1
  firebase_storage: ^11.2.1
  image_picker: ^0.8.7+5
  flutter:
    sdk: flutter
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
