// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIr6AstEQbBUNAFYMuQOolUuGufqeSsMw',
    appId: '1:887978822928:web:ac912fe69a791b1acaa995',
    messagingSenderId: '887978822928',
    projectId: 'flutter-cookbook-6b01c',
    authDomain: 'flutter-cookbook-6b01c.firebaseapp.com',
    storageBucket: 'flutter-cookbook-6b01c.appspot.com',
    measurementId: 'G-0T8EDM6QSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrZ037rmKXF2s1OYC89iHas6WygDsMg2w',
    appId: '1:887978822928:android:e41ac9e62f9765d5caa995',
    messagingSenderId: '887978822928',
    projectId: 'flutter-cookbook-6b01c',
    storageBucket: 'flutter-cookbook-6b01c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZYUvb2CBqQUY8pcW9QHTLPRZCSb7BZkA',
    appId: '1:887978822928:ios:79286f1184e736e7caa995',
    messagingSenderId: '887978822928',
    projectId: 'flutter-cookbook-6b01c',
    storageBucket: 'flutter-cookbook-6b01c.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZYUvb2CBqQUY8pcW9QHTLPRZCSb7BZkA',
    appId: '1:887978822928:ios:79286f1184e736e7caa995',
    messagingSenderId: '887978822928',
    projectId: 'flutter-cookbook-6b01c',
    storageBucket: 'flutter-cookbook-6b01c.appspot.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIr6AstEQbBUNAFYMuQOolUuGufqeSsMw',
    appId: '1:887978822928:web:05419b25bb6704d0caa995',
    messagingSenderId: '887978822928',
    projectId: 'flutter-cookbook-6b01c',
    authDomain: 'flutter-cookbook-6b01c.firebaseapp.com',
    storageBucket: 'flutter-cookbook-6b01c.appspot.com',
    measurementId: 'G-FGTYMPCZBN',
  );
}
